name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout FFmpeg sources
      uses: actions/checkout@v4
      with:
        repository: FFmpeg/FFmpeg
        ref: n8.0
        path: ffmpeg-src
        fetch-depth: 1

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"

    - name: Verify Swift 6 toolchain
      run: |
        set -euo pipefail
        SWIFT_OUTPUT="$(swift --version)"
        echo "$SWIFT_OUTPUT"
        SWIFT_VERSION="$(printf '%s\n' "$SWIFT_OUTPUT" | grep -m1 'Apple Swift version' | awk '{print $4}' || true)"
        SWIFT_MAJOR="${SWIFT_VERSION%%.*}"
        if [ -z "$SWIFT_MAJOR" ] || [ "$SWIFT_MAJOR" -lt 6 ]; then
          echo "Swift 6 or newer is required before building FFmpeg. Detected version: ${SWIFT_VERSION:-unknown}" >&2
          exit 1
        fi

    - name: Build FFmpeg XCFrameworks
      env:
        SWIFT_FFMPEG_SKIP_BINARIES: "1"
        FFMPEG_SOURCE_DIR: ${{ github.workspace }}/ffmpeg-src
      run: swift package plugin build-ffmpeg --force

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test
