name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"

    - name: Show Swift version
      run: swift --version

    - name: Build FFmpeg XCFrameworks
      env:
        SWIFT_FFMPEG_SKIP_BINARIES: "1"
      run: swift package plugin build-ffmpeg --force

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test
